<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>WindrunnerLauncher.Core</RootNamespace>
    <AssemblyName>WindrunnerLauncher.Core</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <PropertyGroup Condition="'$(ProductionTrust)' == 'true'">
    <DefineConstants>$(DefineConstants);PRODUCTION_TRUST</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*" />
    <EmbeddedResource Include="Localization\*.json" />
    <EmbeddedResource Include="Mods\default-addons.json" />
  </ItemGroup>
</Project>
